package ns

import (
	"dna"
)

type Genre struct {
	Id     dna.Int
	Name   dna.String
	NPages dna.Int
}

var SongGenreList *[]Genre = &[]Genre{
	Genre{Id: 99, Name: "Nhạc Xuân", NPages: 129},
	Genre{Id: 73, Name: "Nhạc Không Lời", NPages: 2900},
	Genre{Id: 79, Name: "Pop/Ballad", NPages: 12056},
	Genre{Id: 76, Name: "New Age", NPages: 1326},
	Genre{Id: 90, Name: "House", NPages: 187},
	Genre{Id: 62, Name: "R&B", NPages: 1850},
	Genre{Id: 26, Name: "Rock", NPages: 7595},
	Genre{Id: 64, Name: "Alternative", NPages: 556},
	Genre{Id: 63, Name: "Hiphop/Rap", NPages: 2513},
	Genre{Id: 65, Name: "Country", NPages: 3053},
	Genre{Id: 74, Name: "Folk", NPages: 762},
	Genre{Id: 68, Name: "Dance/Electronic", NPages: 674},
	Genre{Id: 66, Name: "Latin", NPages: 452},
	Genre{Id: 69, Name: "Jazz", NPages: 2864},
	Genre{Id: 70, Name: "Acoustic/Audiophile", NPages: 211},
	Genre{Id: 72, Name: "Soundtrack", NPages: 1220},
	Genre{Id: 77, Name: "Classical", NPages: 493},
	Genre{Id: 75, Name: "Blues", NPages: 611},
	Genre{Id: 108, Name: "Nhạc Giáng Sinh", NPages: 176},
	Genre{Id: 27, Name: "Metal", NPages: 822},
	Genre{Id: 71, Name: "Soul", NPages: 652}}

var AlbumGenreList *[]Genre = &[]Genre{
	Genre{Id: 99, Name: "Nhạc Xuân", NPages: 32},
	Genre{Id: 73, Name: "Nhạc Không Lời", NPages: 517},
	Genre{Id: 79, Name: "Pop/Ballad", NPages: 2831},
	Genre{Id: 76, Name: "New Age", NPages: 281},
	Genre{Id: 90, Name: "House", NPages: 31},
	Genre{Id: 62, Name: "R&B", NPages: 428},
	Genre{Id: 26, Name: "Rock", NPages: 1667},
	Genre{Id: 64, Name: "Alternative", NPages: 95},
	Genre{Id: 63, Name: "Hiphop/Rap", NPages: 442},
	Genre{Id: 65, Name: "Country", NPages: 531},
	Genre{Id: 74, Name: "Folk", NPages: 148},
	Genre{Id: 68, Name: "Dance/Electronic", NPages: 142},
	Genre{Id: 66, Name: "Latin", NPages: 80},
	Genre{Id: 69, Name: "Jazz", NPages: 496},
	Genre{Id: 70, Name: "Acoustic/Audiophile", NPages: 41},
	Genre{Id: 72, Name: "Soundtrack", NPages: 223},
	Genre{Id: 77, Name: "Classical", NPages: 67},
	Genre{Id: 75, Name: "Blues", NPages: 105},
	Genre{Id: 108, Name: "Nhạc Giáng Sinh", NPages: 53},
	Genre{Id: 27, Name: "Metal", NPages: 184},
	Genre{Id: 71, Name: "Soul", NPages: 128}}

var CatTags dna.StringArray = dna.StringArray{
	"",
	"Nhạc Trẻ",
	"Nhạc Trữ Tình",
	"Nhạc Cách Mạng",
	"Nhạc Trịnh ",
	"Nhạc Tiền Chiến",
	"Nhạc Dân Tộc",
	"Nhạc Thiếu Nhi",
	"Nhạc Không Lời",
	"Rock Việt",
	"Nhạc Hải Ngoại",
	"Nhạc Quê Hương",
	"Nhạc Việt Nam",
	"Nhạc Quốc Tế",
	"Rap Việt - Hiphop",
	"Nhạc Hoa",
	"Nhạc Hàn",
	"Nhạc Pháp",
	"Nhạc Các Nước Khác",
	"Classical",
	"Nhạc Phim",
	"Nhạc Âu Mỹ",
	"Pop",
	"Rock",
	"Hiphop/Rap",
	"Country",
	"Jazz",
	"Hiphop",
	"Latin",
	"",
	"Thể Loại",
	"Dance/Electronic",
	"Nhạc Nhật",
	"Chưa phân loại",
	"",
	"Style",
	"Acoustic/Audiophile",
	"Soul",
	"Reggae",
	"Metal",
	"New Age",
	"R&B",
	"Folk",
	"Opera",
	"TV Shows",
	"VMVC 2011",
	"Cặp Đôi Hoàn Hảo",
	"Bài Hát Yêu Thích",
	"Vietnam's Got Talent",
	"Nhạc Chủ Đề",
	"Nhạc 8/3",
	"Nhạc chủ đề",
	"Nhạc 8/3",
	"Mừng QT phụ nữ 8/3",
	"Nhạc Sàn",
	"Nhạc Bà Bầu & Baby",
	"Nhạc Spa | Thư Giãn",
	"Nhạc Đám Cưới Hay",
	"Sách Nói",
	"Radio - Cảm Xúc",
	"The Voice - Giọng Hát Việt",
	"Vietnam Idol 2012",
	"Nhạc Tuyển Tập",
	"Shining Show",
	"Gương Mặt Thân Quen",
	"Ngâm Thơ",
	"Fanmade / Radio",
	"Nhạc Game"}
